require:
  - solidus_dev_support/rubocop

inherit_gem:
  solidus_dev_support: .rubocop.yml

AllCops:
  NewCops: disable
  Exclude:
    - bin/*
    - spec/dummy/**/*
    - vendor/**/*

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/**/*

Gemspec/OrderedDependencies:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/MessageChain:
  Enabled: false
